play=1;
axHndl=gca;
figNumber=gcf;
hndlList=get(figNumber,'UserData');

set(figNumber,'Backingstore','off');
% grid on
% The graphics axis limits are set to values known 
% to contain the solution.
set(axHndl, ...
   'Userdata',play, ...
   'Drawmode','fast', ...
   'Visible','on', ...
   'NextPlot','add', ...
   'Userdata',play, ...
   'xgrid','on', ...
   'ygrid','on', ...
   'gridlinestyle','-');

% axis([0 12 -0.2 1.2])

xlabel('time/(s)')
ylabel('x')

cla;

bodyx1 = line( ...
   'color','r', ...
   'LineStyle','-', ...
   'erase','xor', ...
   'xdata',[],'ydata',[]);

bodyx2 = line( ...
   'color','g', ...
   'LineStyle','-', ...
   'erase','xor', ...
   'xdata',[],'ydata',[]);

bodyx3 = line( ...
   'color','b', ...
   'LineStyle','-', ...
   'erase','xor', ...
   'xdata',[],'ydata',[]);

legend('Runge-Kutta 3rd', 'EULER', 'TRAPEZOID')
title('Simulation Results ')