%%
figure(1)
    play=1;
    axHnd1=gca;
    figNumber=gcf;
    %  hndlList=get(figNumber,'UserData');

    set(figNumber,'Backingstore','off');
    % grid on
    % The graphics axis limits are set to values known 
    % to contain the solution.
    set(axHnd1, ...
       'Userdata',play, ...
       'Drawmode','fast', ...
       'Visible','on', ...
       'NextPlot','add', ...
       'Userdata',play, ...
       'xgrid','on', ...
       'ygrid','on', ...
       'gridlinestyle','-');

%     axis([0 12 -0.2 1.2])

    xlabel('time/(s)')
    ylabel('x')

    cla;

    bodyx1 = line( ...
       'color','r', ...
       'LineStyle','-', ...
       'erase','xor', ...
       'xdata',[],'ydata',[]);

    bodyx2 = line( ...
       'color','g', ...
       'LineStyle','-', ...
       'erase','xor', ...
       'xdata',[],'ydata',[]);

    bodyx3 = line( ...
       'color','b', ...
       'LineStyle','-', ...
       'erase','xor', ...
       'xdata',[],'ydata',[]);

    legend('Runge-Kutta 3rd', 'EULER', 'TRAPEZOID')
    title('Simulation Results')

%%
figure(2)
    play=2;
    axHnd2=gca;
    figNumber=gcf;
    hndlList=get(figNumber,'UserData');

    set(figNumber,'Backingstore','off');
    % grid on
    % The graphics axis limits are set to values known 
    % to contain the solution.
    set(axHnd2, ...
       'Userdata',play, ...
       'Drawmode','fast', ...
       'Visible','on', ...
       'NextPlot','add', ...
       'Userdata',play, ...
       'xgrid','on', ...
       'ygrid','on', ...
       'gridlinestyle','-');

    %  axis([0 5 -0.2 1.2])

    xlabel('time/(s)')
    ylabel('x')

    cla;

    bodyx4 = line( ...
       'color','r', ...
       'LineStyle','-', ...
       'erase','xor', ...
       'xdata',[],'ydata',[]);

    legend('The exact solution')
    title('Exact Results')

%%
figure(3)
    play=3;
    axHnd3=gca;
    figNumber=gcf;
    hndlList=get(figNumber,'UserData');

    set(figNumber,'Backingstore','off');
    % grid on
    % The graphics axis limits are set to values known 
    % to contain the solution.
    set(axHnd3, ...
       'Userdata',play, ...
       'Drawmode','fast', ...
       'Visible','on', ...
       'NextPlot','add', ...
       'Userdata',play, ...
       'xgrid','on', ...
       'ygrid','on', ...
       'gridlinestyle','-');

    %  axis([0 5 -0.2 1.2])

    xlabel('step time')
    ylabel('error')

    cla;

    bodyx5 = line( ...
       'color','r', ...
       'LineStyle','-', ...
       'erase','xor', ...
       'xdata',[],'ydata',[]);
   bodyx6 = line( ...
       'color','g', ...
       'LineStyle','-', ...
       'erase','xor', ...
       'xdata',[],'ydata',[]);
   bodyx7 = line( ...
       'color','b', ...
       'LineStyle','-', ...
       'erase','xor', ...
       'xdata',[],'ydata',[]);

    legend('RK3 Error', 'EUL Error', 'TRAPEZOID Error')
    title('Simulation Errors')