play=1;
axHndl=gca;
figNumber=gcf;
hndlList=get(figNumber,'UserData');

set(figNumber,'Backingstore','off');

% The graphics axis limits are set to values known 
% to contain the solution.
set(axHndl, ...
   'XLim',[0 40],'YLim',[-35 10],'ZLim',[-10 40], ...
   'Userdata',play, ...
   'XTick',[],'YTick',[],'ZTick',[], ...
   'Drawmode','fast', ...
   'Visible','on', ...
   'NextPlot','add', ...
   'Userdata',play, ...
   'View',[-37.5,30]);

axis([-1 1 -1 1 -1 1])
axis square
grid on
xlabel('x-ECI')
ylabel('y-ECI')
zlabel('z-ECI')

cla;
bodyx = line( ...
   'color','r', ...
   'LineStyle','-', ...
   'erase','xor', ...
   'xdata',[],'ydata',[],'zdata',[]);
bodyy = line( ...
   'color','g', ...
   'LineStyle','-', ...
   'erase','xor', ...
   'xdata',[],'ydata',[],'zdata',[]);
bodyz = line( ...
   'color','b', ...
   'LineStyle','-', ...
   'erase','xor', ...
   'xdata',[],'ydata',[],'zdata',[]);

legend('x-Body','y-Body','z-Body')
title('Lage des Körpers ')
 
